<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create units
        $kg = Unit::firstOrCreate(['name' => 'Kilogram']);
        $litre = Unit::firstOrCreate(['name' => 'Litre']);
        $piece = Unit::firstOrCreate(['name' => 'Piece']);
        $dozen = Unit::firstOrCreate(['name' => 'Dozen']);
        $gram = Unit::firstOrCreate(['name' => 'Gram']);
        $pack = Unit::firstOrCreate(['name' => 'Pack']);

        // Ingredients/Products for restaurant
        $products = [
            // Rice & Grains
            [
                'name' => 'Basmati Rice',
                'sku' => 'RICE-001',
                'unit_id' => $kg->id,
                'purchase_cost' => 120.00,
                'default_price' => 150.00,
                'minimum_stock' => 50,
                'reorder_level' => 100,
                'group' => 'Grains',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Maida Flour',
                'sku' => 'FLOUR-001',
                'unit_id' => $kg->id,
                'purchase_cost' => 80.00,
                'default_price' => 100.00,
                'minimum_stock' => 30,
                'reorder_level' => 50,
                'group' => 'Grains',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Atta Flour',
                'sku' => 'FLOUR-002',
                'unit_id' => $kg->id,
                'purchase_cost' => 75.00,
                'default_price' => 95.00,
                'minimum_stock' => 30,
                'reorder_level' => 50,
                'group' => 'Grains',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Vegetables
            [
                'name' => 'Onion',
                'sku' => 'VEG-001',
                'unit_id' => $kg->id,
                'purchase_cost' => 60.00,
                'default_price' => 80.00,
                'minimum_stock' => 20,
                'reorder_level' => 40,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Potato',
                'sku' => 'VEG-002',
                'unit_id' => $kg->id,
                'purchase_cost' => 50.00,
                'default_price' => 70.00,
                'minimum_stock' => 25,
                'reorder_level' => 50,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Tomato',
                'sku' => 'VEG-003',
                'unit_id' => $kg->id,
                'purchase_cost' => 80.00,
                'default_price' => 100.00,
                'minimum_stock' => 15,
                'reorder_level' => 30,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Garlic',
                'sku' => 'VEG-004',
                'unit_id' => $kg->id,
                'purchase_cost' => 200.00,
                'default_price' => 250.00,
                'minimum_stock' => 5,
                'reorder_level' => 10,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Ginger',
                'sku' => 'VEG-005',
                'unit_id' => $kg->id,
                'purchase_cost' => 180.00,
                'default_price' => 220.00,
                'minimum_stock' => 5,
                'reorder_level' => 10,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Green Chilli',
                'sku' => 'VEG-006',
                'unit_id' => $kg->id,
                'purchase_cost' => 120.00,
                'default_price' => 150.00,
                'minimum_stock' => 3,
                'reorder_level' => 5,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Coriander Leaves',
                'sku' => 'VEG-007',
                'unit_id' => $kg->id,
                'purchase_cost' => 100.00,
                'default_price' => 130.00,
                'minimum_stock' => 2,
                'reorder_level' => 5,
                'group' => 'Vegetables',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Spices
            [
                'name' => 'Cumin Powder (Jeera)',
                'sku' => 'SPC-001',
                'unit_id' => $kg->id,
                'purchase_cost' => 400.00,
                'default_price' => 500.00,
                'minimum_stock' => 2,
                'reorder_level' => 5,
                'group' => 'Spices',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Turmeric Powder',
                'sku' => 'SPC-002',
                'unit_id' => $kg->id,
                'purchase_cost' => 300.00,
                'default_price' => 380.00,
                'minimum_stock' => 2,
                'reorder_level' => 5,
                'group' => 'Spices',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Red Chilli Powder',
                'sku' => 'SPC-003',
                'unit_id' => $kg->id,
                'purchase_cost' => 350.00,
                'default_price' => 450.00,
                'minimum_stock' => 2,
                'reorder_level' => 5,
                'group' => 'Spices',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Garam Masala',
                'sku' => 'SPC-004',
                'unit_id' => $kg->id,
                'purchase_cost' => 500.00,
                'default_price' => 600.00,
                'minimum_stock' => 1,
                'reorder_level' => 3,
                'group' => 'Spices',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Salt',
                'sku' => 'SPC-005',
                'unit_id' => $kg->id,
                'purchase_cost' => 30.00,
                'default_price' => 40.00,
                'minimum_stock' => 10,
                'reorder_level' => 20,
                'group' => 'Spices',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Dairy
            [
                'name' => 'Milk',
                'sku' => 'DAIRY-001',
                'unit_id' => $litre->id,
                'purchase_cost' => 80.00,
                'default_price' => 100.00,
                'minimum_stock' => 20,
                'reorder_level' => 40,
                'group' => 'Dairy',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Butter',
                'sku' => 'DAIRY-002',
                'unit_id' => $kg->id,
                'purchase_cost' => 600.00,
                'default_price' => 750.00,
                'minimum_stock' => 5,
                'reorder_level' => 10,
                'group' => 'Dairy',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Paneer',
                'sku' => 'DAIRY-003',
                'unit_id' => $kg->id,
                'purchase_cost' => 350.00,
                'default_price' => 450.00,
                'minimum_stock' => 5,
                'reorder_level' => 10,
                'group' => 'Dairy',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Ghee',
                'sku' => 'DAIRY-004',
                'unit_id' => $litre->id,
                'purchase_cost' => 1200.00,
                'default_price' => 1500.00,
                'minimum_stock' => 3,
                'reorder_level' => 5,
                'group' => 'Dairy',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Yogurt (Dahi)',
                'sku' => 'DAIRY-005',
                'unit_id' => $kg->id,
                'purchase_cost' => 120.00,
                'default_price' => 150.00,
                'minimum_stock' => 10,
                'reorder_level' => 20,
                'group' => 'Dairy',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Meat
            [
                'name' => 'Chicken',
                'sku' => 'MEAT-001',
                'unit_id' => $kg->id,
                'purchase_cost' => 350.00,
                'default_price' => 450.00,
                'minimum_stock' => 10,
                'reorder_level' => 20,
                'group' => 'Meat',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Mutton (Khasi)',
                'sku' => 'MEAT-002',
                'unit_id' => $kg->id,
                'purchase_cost' => 1200.00,
                'default_price' => 1500.00,
                'minimum_stock' => 5,
                'reorder_level' => 10,
                'group' => 'Meat',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Buff Meat',
                'sku' => 'MEAT-003',
                'unit_id' => $kg->id,
                'purchase_cost' => 800.00,
                'default_price' => 1000.00,
                'minimum_stock' => 8,
                'reorder_level' => 15,
                'group' => 'Meat',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Eggs',
                'sku' => 'MEAT-004',
                'unit_id' => $dozen->id,
                'purchase_cost' => 180.00,
                'default_price' => 220.00,
                'minimum_stock' => 10,
                'reorder_level' => 20,
                'group' => 'Meat',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Oil
            [
                'name' => 'Vegetable Oil',
                'sku' => 'OIL-001',
                'unit_id' => $litre->id,
                'purchase_cost' => 180.00,
                'default_price' => 220.00,
                'minimum_stock' => 15,
                'reorder_level' => 30,
                'group' => 'Oil',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Mustard Oil',
                'sku' => 'OIL-002',
                'unit_id' => $litre->id,
                'purchase_cost' => 200.00,
                'default_price' => 250.00,
                'minimum_stock' => 10,
                'reorder_level' => 20,
                'group' => 'Oil',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Ghee (Pure)',
                'sku' => 'OIL-003',
                'unit_id' => $litre->id,
                'purchase_cost' => 1500.00,
                'default_price' => 1800.00,
                'minimum_stock' => 5,
                'reorder_level' => 10,
                'group' => 'Oil',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Beverages
            [
                'name' => 'Tea Leaves',
                'sku' => 'BEV-001',
                'unit_id' => $kg->id,
                'purchase_cost' => 600.00,
                'default_price' => 750.00,
                'minimum_stock' => 3,
                'reorder_level' => 5,
                'group' => 'Beverages',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Coffee Powder',
                'sku' => 'BEV-002',
                'unit_id' => $kg->id,
                'purchase_cost' => 800.00,
                'default_price' => 1000.00,
                'minimum_stock' => 2,
                'reorder_level' => 4,
                'group' => 'Beverages',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],
            [
                'name' => 'Sugar',
                'sku' => 'BEV-003',
                'unit_id' => $kg->id,
                'purchase_cost' => 90.00,
                'default_price' => 110.00,
                'minimum_stock' => 15,
                'reorder_level' => 30,
                'group' => 'Beverages',
                'item_type' => 'ingredient',
                'status' => 'active',
            ],

            // Packaging
            [
                'name' => 'Takeaway Boxes (Small)',
                'sku' => 'PKG-001',
                'unit_id' => $pack->id,
                'purchase_cost' => 5.00,
                'default_price' => 8.00,
                'minimum_stock' => 50,
                'reorder_level' => 100,
                'group' => 'Packaging',
                'item_type' => 'consumable',
                'status' => 'active',
            ],
            [
                'name' => 'Takeaway Boxes (Large)',
                'sku' => 'PKG-002',
                'unit_id' => $pack->id,
                'purchase_cost' => 8.00,
                'default_price' => 12.00,
                'minimum_stock' => 50,
                'reorder_level' => 100,
                'group' => 'Packaging',
                'item_type' => 'consumable',
                'status' => 'active',
            ],
            [
                'name' => 'Paper Plates',
                'sku' => 'PKG-003',
                'unit_id' => $pack->id,
                'purchase_cost' => 3.00,
                'default_price' => 5.00,
                'minimum_stock' => 100,
                'reorder_level' => 200,
                'group' => 'Packaging',
                'item_type' => 'consumable',
                'status' => 'active',
            ],
            [
                'name' => 'Plastic Spoons',
                'sku' => 'PKG-004',
                'unit_id' => $pack->id,
                'purchase_cost' => 2.00,
                'default_price' => 3.00,
                'minimum_stock' => 200,
                'reorder_level' => 500,
                'group' => 'Packaging',
                'item_type' => 'consumable',
                'status' => 'active',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                array_merge($product, ['tenant_id' => 1])
            );
        }
    }
}
